### PR TITLE
Preliminary Chameleon usage in QMCkl

### PR DESCRIPTION
**Pull request by v1j4y**
This is a preliminary pull request to set up building with Chameleon.

- [x] Build with chameleon
- [ ] Use chameleon via define flags
- [ ] Example version of jastrow factor with chameleon dgemm

### CODE REVIEW

**Comment by scemama** [comment]
You have conflicts because I renamed some functions

**Comment by scemama** [comment]
You could add `--with-chameleon` in configure to set the environment variables you mention in the `README.md` and it will set a variable `HAS_CHAMELEON` in `include/config.h` that you can test with `ifdef`.

**Comment by scemama** [comment]
Could you make the pull request for this not on master but on a special branch for the HPC version?

**Comment by v1j4y** [comment]
> You have conflicts because I renamed some functions

Ok, yes I did a pull request without checking if the base had changes. I'll try to merge my branch with master.

**Comment by v1j4y** [comment]
> You could add `--with-chameleon` in configure to set the environment variables you mention in the `README.md` and it will set a variable `HAS_CHAMELEON` in `include/config.h` that you can test with `ifdef`.

Yes ! I already have set up the `configure.ac` script to use `--with-chameleon` and it already correctly sets up `HAS_CHAMELEON` in the `include/config.h` file. Is this what you wanted ?

**Comment by v1j4y** [comment]
> Could you make the pull request for this not on master but on a special branch for the HPC version?

OK, I'll close this and open a new pull request on the hpc branch.

**Comment by scemama** [comment]
Perfect!

**Pull request closed without merging**
